[package]
name = "sxt-proof-of-sql-sdk-wasm"
edition.workspace = true
repository.workspace = true
version.workspace = true
license-file.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
ark-serialize = { workspace = true }
arrow = { workspace = true }
gloo-utils = { workspace = true }
hex = { workspace = true, features = ["serde"] }
lazy_static = { workspace = true }
proof-of-sql = { workspace = true }
postcard = { workspace = true }
subxt = { workspace = true }
serde = { workspace = true }
sxt-proof-of-sql-sdk.workspace = true
wasm-bindgen = { workspace = true }
