name: Release
on:
  push:
    branches:
      - main
permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  release:
    name: Run Release Manager
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
          # Pull all previous tags
          fetch-depth: 0
          fetch-tags: true

      - name: Conventional Changelog Action
        if: github.ref_name == 'main'
        id: conventional-changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          skip-git-pull: true
          skip-version-file: true
          git-push: false
          skip-on-empty: false # Always create commit

      - name: Bump package.json Version
        working-directory: ./node/src
        run: |
          TAG=${{ steps.conventional-changelog.outputs.tag }}
          VERSION=${TAG#v}
          echo "Bumping npm package version to $VERSION"
          npm version $VERSION --no-git-tag-version

      - name: Commit package.json Version
        working-directory: ./node/src
        run: |
          TAG=${{ steps.conventional-changelog.outputs.tag }}
          VERSION=${TAG#v}
          git add package.json
          git commit -m "chore(release): bump npm package version to $VERSION [skip ci]"

      - name: Push Conventional Changelog
        if: github.ref_name == 'main'
        uses: ad-m/github-push-action@master
        id: push
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          branch: ${{ github.ref }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: github.ref_name == 'main'
        with:
          tag: ${{ steps.conventional-changelog.outputs.tag }}
          body: ${{ steps.conventional-changelog.outputs.changelog }}
          token: ${{ steps.app-token.outputs.token }} # Using Github Auth token created in step above
          makeLatest: true

      - name: Install stable toolchain
        run: curl https://sh.rustup.rs -sSf | bash -s -- -y --profile minimal && source ~/.cargo/env && rustup toolchain install

      - name: Install build dependencies
        run: export DEBIAN_FRONTEND=non-interactive && sudo apt-get update && sudo apt-get install -y clang lld protobuf-compiler

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build wasm binary
        run: wasm-pack build --release --target deno --no-typescript -- --no-default-features --features wasm

      - name: Build javascript index
        run: |
          chmod +x ./node/src/build_index.sh
          ./node/src/build_index.sh wasm/pkg

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@spaceandtimelabs'

      - name: Publish to npm
        working-directory: ./node/src
        run: |
          npm publish --access public --non-interactive
