name: Release
on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: 'The Git reference (branch, tag, or commit SHA) to release from'
        required: true
        default: 'main'

jobs:
  release:
    name: Run Release Manager
    if: "!contains(github.event.head_commit.message, 'chore(release):')"
    runs-on: ubuntu-latest

    steps:
      - name: Load Secrets
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_HOST }}
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          GITHUB_APP_ID: op://op-github-devops/cosmic-agent-labs/app-id
          GITHUB_PRIVATE_KEY: op://op-github-devops/cosmic-agent-labs/private-key
          NODE_AUTH_TOKEN: op://op-github-devops/npmjs-registry/token

      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ env.GITHUB_APP_ID }}
          private-key: ${{ env.GITHUB_PRIVATE_KEY }}